### PR TITLE
Bump pdfxchangeviewer 2.5.212

### PR DESCRIPTION
**Pull request by TomOne**
If you are not planning to provide fast updates for this package, please add me as co-owner for it.

### CODE REVIEW

**Comment by TomOne** [comment]
Sir, please don’t ignore this. If you can’t manage to maintain this package, make me co-owner of it.

**Comment by cwldev** [comment]
How about offering a few more details about what's needed? I'm happy to do so if I understand what you're asking. Make you an owner where exactly? How exactly?

**Comment by TomOne** [comment]
Thanks for merging this. You can make me a co-owner if you log into your chocolatey.org account, go to https://chocolatey.org/packages/PDFXChangeViewer and click on “Manage Owners” on the left side. Then you can add me (user “purity”) as co-owner of your PDFXChangeViewer package an we both can update the package. I think that makes sense and then I don’t have to bother you with pull requests again. :)

**Comment by TomOne** [comment]
Can you please do this? After so many attempts to contact you I think you certainly want that we both have less work with this package. :)

**Pull request merged**
