### PR TITLE
Total Commander 8.5. Beta (7)

### PR DESCRIPTION
**Pull request by Flyingdot**
Hi

I just found your Total Commander Package. Because I use the 8.5. Version and there is no package for that, I forked yours.
I can help you with future updates as well.

thx

### CODE REVIEW

**Comment by Flyingdot** [comment]
forget to mention - I didn't uploaded the package. Maybe you can add me as co-owner so that I can help you for future releases.

**Comment by cwldev** [comment]
Yes, thanks.. Total Commander is only at 8.0.1 though.. I didn't know 8.5
was out..

I'll look at this today when I get the chance. Thanks for the help.

K

**Comment by TobiX** [comment]
Any progress? Total Commander 8.50 is stable since ~2 months, 8.51 is alread RC...

**Comment by piotr-cz** [comment]
+1
would be nice to have the uninstall script too (`tools\chocolateyUninstall.ps1`)

**Comment by mjiderhamn** [comment]
8.51a has been out since April 30, last year. Would be nice if this Chocolatey package was updated.

**Comment by mjiderhamn** [comment]
Pull request #5 superseedes this one.

**Pull request closed without merging**
